import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import StyledComponentsRegistry from "../../lib/registry";
import "./globals.css";
import Container from "../../components/Container";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <Container>{children}</Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

//import localFont from "next/font/local";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
//  <body className={`${geistSans.variable} ${geistMono.variable}`}>
